import os
os.environ['ETS_TOOLKIT'] = 'qt4'
import imp
try:
    imp.find_module('PySide') # test if PySide if available
except ImportError:
    os.environ['QT_API'] = 'pyqt5' # signal to pyface that PyQt4 should be used
from traits.etsconfig.api import ETSConfig
ETSConfig.toolkit = 'qt4'
import sys
from PyQt5 import QtWidgets
from PyQt5.QtWidgets import QApplication, QHBoxLayout, QWidget
from pyface.qt import QtGui, QtCore
from traits.api import HasTraits, Instance, on_trait_change
from traitsui.api import View, Item
from mayavi.core.ui.api import MayaviScene, MlabSceneModel, SceneEditor
import matplotlib
from matplotlib import cm, colors
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg
from matplotlib.figure import Figure
from mpl_toolkits.basemap import Basemap
from utils.GeoPotential_utils import *


#The actual visualization of Mayavi
class Visualization(HasTraits):
    scene = Instance(MlabSceneModel, ())

    @on_trait_change('scene.activated')
    def update_plot(self):
        path = './data/GeoPotencial-data/Geoid&Undulation/'
        X = load_txt(path+'X.txt')
        Y = load_txt(path+'Y.txt')
        Z = load_txt(path+'Z.txt')
        N = load_txt(path+'N.txt')
        self.scene.mlab.clf()
        self.scene.mlab.mesh(X, Y, Z, scalars=N, colormap='jet')
        self.scene.mlab.view(-85,85)

    view = View(Item('scene', editor=SceneEditor(scene_class=MayaviScene),
                     height=250, width=300, show_label=False),
                resizable=True)


# The QWidget containing the visualization, this is pure PyQt4 code.
# Mayavi Widget
class MayaviQWidget(QtGui.QWidget):
    def __init__(self, parent=None):
        QtGui.QWidget.__init__(self, parent)
        layout = QtGui.QVBoxLayout(self)
        layout.setContentsMargins(0,0,0,0)
        layout.setSpacing(0)
        self.visualization = Visualization()

        # The edit_traits call will generate the widget to embed.
        self.ui = self.visualization.edit_traits(parent=self,
                                                 kind='subpanel').control
        layout.addWidget(self.ui)
        #self.ui.setParent(self)

# Figure Canvas Class for matoplotlib plots
class MplCanvas(FigureCanvasQTAgg):
    def __init__(self, parent=None, width=5, height=4, dpi=100):
        self.fig = Figure(figsize=(width, height), dpi=dpi)
        self.axes = self.fig.add_subplot(111)
        super(MplCanvas, self).__init__(self.fig)

# Represent GeoPotential Window Class
class GeoPotential_MainWindow(QWidget):
    def __init__(self, *args):
        QWidget.__init__(self, *args)
        self.resize(1472, 819)
        self.originalPalette = QApplication.palette()
        self.setWindowIcon(QtGui.QIcon('icon.ico'))

        self.centralwidget = QtWidgets.QWidget()
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")

        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")

        # Tab Geoid
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(589, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(111, 41))
        self.label.setMaximumSize(QtCore.QSize(111, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 35, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(25)
        self.gridLayout_2.setObjectName("gridLayout_2")

        # Widget mayavi geoid
        self.container = QtGui.QWidget()
        self.widget_2 = MayaviQWidget(self.container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setStyleSheet("background-color: rgb(203, 203, 203);")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2.addWidget(self.widget_2, 1, 1, 1, 3)

        # Widget matplotlib undulation
        self.widget = MplCanvas(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(32)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setStyleSheet("background-color: rgb(203, 203, 203);")
        self.widget.setObjectName("widget")
        self.set_Undulation()
        self.gridLayout_2.addWidget(self.widget, 0, 0, 3, 1)

        spacerItem2 = QtWidgets.QSpacerItem(20, 75, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 2, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 75, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem3, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 2, 0, 1, 3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 45, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem4, 1, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem5, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")

        # Tab Coeff Vis
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_27.setObjectName("gridLayout_27")

        # Widget pot for Coeff
        self.widget_11 = MplCanvas(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_11.sizePolicy().hasHeightForWidth())
        self.widget_11.setSizePolicy(sizePolicy)
        self.widget_11.setStyleSheet("background-color: rgb(203, 203, 203);")
        self.widget_11.setObjectName("widget_11")
        self.gridLayout_27.addWidget(self.widget_11, 0, 0, 1, 1)

        self.gridLayout_21.addWidget(self.groupBox_9, 0, 1, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_26.setObjectName("gridLayout_26")
        spacerItem6 = QtWidgets.QSpacerItem(462, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_26.addItem(spacerItem6, 1, 0, 1, 1)
        self.gridLayout_25 = QtWidgets.QGridLayout()
        self.gridLayout_25.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.label_80 = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_80.sizePolicy().hasHeightForWidth())
        self.label_80.setSizePolicy(sizePolicy)
        self.label_80.setObjectName("label_80")
        self.gridLayout_25.addWidget(self.label_80, 1, 6, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_77.sizePolicy().hasHeightForWidth())
        self.label_77.setSizePolicy(sizePolicy)
        self.label_77.setObjectName("label_77")
        self.gridLayout_25.addWidget(self.label_77, 1, 3, 1, 1)
        self.label_79 = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_79.sizePolicy().hasHeightForWidth())
        self.label_79.setSizePolicy(sizePolicy)
        self.label_79.setObjectName("label_79")
        self.gridLayout_25.addWidget(self.label_79, 1, 5, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_81.sizePolicy().hasHeightForWidth())
        self.label_81.setSizePolicy(sizePolicy)
        self.label_81.setObjectName("label_81")
        self.gridLayout_25.addWidget(self.label_81, 1, 7, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_78.sizePolicy().hasHeightForWidth())
        self.label_78.setSizePolicy(sizePolicy)
        self.label_78.setObjectName("label_78")
        self.gridLayout_25.addWidget(self.label_78, 1, 4, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_82.sizePolicy().hasHeightForWidth())
        self.label_82.setSizePolicy(sizePolicy)
        self.label_82.setObjectName("label_82")
        self.gridLayout_25.addWidget(self.label_82, 1, 8, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_83.sizePolicy().hasHeightForWidth())
        self.label_83.setSizePolicy(sizePolicy)
        self.label_83.setObjectName("label_83")
        self.gridLayout_25.addWidget(self.label_83, 1, 9, 1, 1)

        # Slider Coeff
        self.horizontalSlider_5 = QtWidgets.QSlider(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_5.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_5.setSizePolicy(sizePolicy)
        self.horizontalSlider_5.setMinimum(1)
        self.horizontalSlider_5.setMaximum(10)
        self.horizontalSlider_5.setPageStep(1)
        self.horizontalSlider_5.setTracking(False)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        # Calls function update_coeff_vis() when slider in this tab is moved
        self.horizontalSlider_5.valueChanged.connect(self.update_coeff_vis) # or sliderReleased insted of valueChanged
        self.gridLayout_25.addWidget(self.horizontalSlider_5, 0, 0, 1, 10)

        self.label_76 = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_76.sizePolicy().hasHeightForWidth())
        self.label_76.setSizePolicy(sizePolicy)
        self.label_76.setObjectName("label_76")
        self.gridLayout_25.addWidget(self.label_76, 1, 2, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_74.sizePolicy().hasHeightForWidth())
        self.label_74.setSizePolicy(sizePolicy)
        self.label_74.setObjectName("label_74")
        self.gridLayout_25.addWidget(self.label_74, 1, 0, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_75.sizePolicy().hasHeightForWidth())
        self.label_75.setSizePolicy(sizePolicy)
        self.label_75.setObjectName("label_75")
        self.gridLayout_25.addWidget(self.label_75, 1, 1, 1, 1)
        self.gridLayout_26.addLayout(self.gridLayout_25, 1, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(465, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_26.addItem(spacerItem7, 0, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_26.addItem(spacerItem8, 2, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(462, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_26.addItem(spacerItem9, 1, 2, 1, 1)
        self.gridLayout_21.addWidget(self.groupBox_8, 1, 1, 1, 2)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_28.setObjectName("gridLayout_28")

        # Widget accel for Coeff
        self.widget_12 = MplCanvas(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_12.sizePolicy().hasHeightForWidth())
        self.widget_12.setSizePolicy(sizePolicy)
        self.widget_12.setStyleSheet("background-color: rgb(203, 203, 203);")
        self.widget_12.setObjectName("widget_12")
        self.gridLayout_28.addWidget(self.widget_12, 0, 0, 1, 1)

        self.gridLayout_21.addWidget(self.groupBox_10, 0, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(0, 554, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_21.addItem(spacerItem10, 0, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(0, 130, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_21.addItem(spacerItem11, 1, 0, 1, 1)
        self.gridLayout_22.addLayout(self.gridLayout_21, 1, 0, 1, 3)
        spacerItem12 = QtWidgets.QSpacerItem(522, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem12, 0, 0, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.gridLayout_22.addWidget(self.label_62, 0, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_22.addItem(spacerItem13, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")

        self.update_coeff_vis()

        # Tab Pot Vis
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem14 = QtWidgets.QSpacerItem(500, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem14, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_9.addWidget(self.label_2, 0, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(200, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem15, 0, 2, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")

        # Widget pot for h
        self.widget_3 = MplCanvas(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setStyleSheet("background-color: rgb(203, 203, 203);")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_7.addWidget(self.widget_3, 1, 0, 1, 3)

        spacerItem16 = QtWidgets.QSpacerItem(20, 42, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_7.addItem(spacerItem16, 2, 1, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 1, 8, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 1, 10, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 1, 6, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 1, 1, 1, 1)

        # Slider h of pot for h
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setMinimum(220)
        self.horizontalSlider.setMaximum(230)
        self.horizontalSlider.setSingleStep(1)
        self.horizontalSlider.setPageStep(1)
        self.horizontalSlider.setProperty("value", 220)
        self.horizontalSlider.setSliderPosition(223)
        self.horizontalSlider.setTracking(False)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setInvertedControls(False)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider.setTickInterval(1)
        self.horizontalSlider.setObjectName("horizontalSlider")
        # Calls update_pot_onSphere_vis() function when slider for h in this tab is moved
        self.horizontalSlider.valueChanged.connect(self.update_pot_onSphere_vis) # or sliderReleased insted of valueChanged
        self.gridLayout_5.addWidget(self.horizontalSlider, 0, 1, 1, 11)

        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 1, 11, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 1, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 1, 9, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 1, 7, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 1, 5, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 1, 12, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_5, 3, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem17, 3, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 35, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_7.addItem(spacerItem18, 4, 1, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(0, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_7.addItem(spacerItem19, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem20 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_8.addItem(spacerItem20, 0, 1, 1, 1)

        # Widget pot for theta=0
        self.widget_4 = MplCanvas(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setStyleSheet("background-color: rgb(203, 203, 203);")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_8.addWidget(self.widget_4, 1, 0, 1, 4)

        spacerItem21 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_8.addItem(spacerItem21, 2, 2, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem22, 3, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 1, 6, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 1, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_6.addWidget(self.label_21, 1, 5, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 1, 4, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_6.addWidget(self.label_23, 1, 7, 1, 1)

        # Slider h of pot for theta=0
        self.horizontalSlider_2 = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider_2.setMinimum(2)
        self.horizontalSlider_2.setMaximum(8)
        self.horizontalSlider_2.setSingleStep(1)
        self.horizontalSlider_2.setPageStep(1)
        self.horizontalSlider_2.setProperty("value", 2)
        self.horizontalSlider_2.setSliderPosition(2)
        self.horizontalSlider_2.setTracking(False)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setInvertedAppearance(False)
        self.horizontalSlider_2.setInvertedControls(False)
        self.horizontalSlider_2.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider_2.setTickInterval(1)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        # Calls update_pot_onPlane_vis() function when slider for h when theta=0 in this tab is moved
        self.horizontalSlider_2.valueChanged.connect(self.update_pot_onPlane_vis) # or sliderReleased insted of valueChanged
        self.gridLayout_6.addWidget(self.horizontalSlider_2, 0, 1, 1, 7)

        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 1, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_6.addWidget(self.label_24, 1, 8, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_6.addWidget(self.label_25, 1, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_6, 3, 1, 1, 2)
        spacerItem23 = QtWidgets.QSpacerItem(20, 35, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_8.addItem(spacerItem23, 4, 2, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_4, 1, 0, 1, 3)
        self.tabWidget.addTab(self.tab_2, "")

        self.update_pot_onSphere_vis()
        self.update_pot_onPlane_vis()

        # Tab Accel Vis
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_15.setObjectName("gridLayout_15")
        spacerItem24 = QtWidgets.QSpacerItem(500, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem24, 0, 0, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.gridLayout_15.addWidget(self.label_48, 0, 1, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(200, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_15.addItem(spacerItem25, 0, 2, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_11.setObjectName("gridLayout_11")

        # Widget accel for h
        self.widget_5 = MplCanvas(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setStyleSheet("background-color: rgb(203, 203, 203);")
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_11.addWidget(self.widget_5, 1, 0, 1, 3)

        spacerItem26 = QtWidgets.QSpacerItem(20, 42, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_11.addItem(spacerItem26, 2, 1, 1, 1)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_26 = QtWidgets.QLabel(self.groupBox_3)
        self.label_26.setObjectName("label_26")
        self.gridLayout_12.addWidget(self.label_26, 1, 8, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_3)
        self.label_27.setObjectName("label_27")
        self.gridLayout_12.addWidget(self.label_27, 1, 10, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_3)
        self.label_28.setObjectName("label_28")
        self.gridLayout_12.addWidget(self.label_28, 1, 6, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_3)
        self.label_29.setObjectName("label_29")
        self.gridLayout_12.addWidget(self.label_29, 1, 1, 1, 1)

        # Slider h for accel for h
        self.horizontalSlider_3 = QtWidgets.QSlider(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_3.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_3.setSizePolicy(sizePolicy)
        self.horizontalSlider_3.setMinimum(220)
        self.horizontalSlider_3.setMaximum(230)
        self.horizontalSlider_3.setSingleStep(1)
        self.horizontalSlider_3.setPageStep(1)
        self.horizontalSlider_3.setProperty("value", 220)
        self.horizontalSlider_3.setSliderPosition(223)
        self.horizontalSlider_3.setTracking(False)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setInvertedAppearance(False)
        self.horizontalSlider_3.setInvertedControls(False)
        self.horizontalSlider_3.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider_3.setTickInterval(1)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        # Calls update_g_onSphere_vis() function when slider for h in this tab is moved
        self.horizontalSlider_3.valueChanged.connect(self.update_g_onSphere_vis) # or sliderReleased insted of valueChanged
        self.gridLayout_12.addWidget(self.horizontalSlider_3, 0, 1, 1, 11)

        self.label_30 = QtWidgets.QLabel(self.groupBox_3)
        self.label_30.setObjectName("label_30")
        self.gridLayout_12.addWidget(self.label_30, 1, 11, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox_3)
        self.label_31.setObjectName("label_31")
        self.gridLayout_12.addWidget(self.label_31, 1, 4, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox_3)
        self.label_32.setObjectName("label_32")
        self.gridLayout_12.addWidget(self.label_32, 1, 9, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_3)
        self.label_33.setObjectName("label_33")
        self.gridLayout_12.addWidget(self.label_33, 1, 7, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBox_3)
        self.label_34.setObjectName("label_34")
        self.gridLayout_12.addWidget(self.label_34, 1, 3, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox_3)
        self.label_35.setObjectName("label_35")
        self.gridLayout_12.addWidget(self.label_35, 1, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.groupBox_3)
        self.label_36.setObjectName("label_36")
        self.gridLayout_12.addWidget(self.label_36, 1, 5, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.groupBox_3)
        self.label_37.setObjectName("label_37")
        self.gridLayout_12.addWidget(self.label_37, 1, 12, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.groupBox_3)
        self.label_38.setObjectName("label_38")
        self.gridLayout_12.addWidget(self.label_38, 1, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_12, 3, 1, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem27, 3, 0, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(20, 35, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_11.addItem(spacerItem28, 4, 1, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(0, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_11.addItem(spacerItem29, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_13.setObjectName("gridLayout_13")
        spacerItem30 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_13.addItem(spacerItem30, 0, 1, 1, 1)

        # Widget accel for theta=0
        self.widget_6 = MplCanvas(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setStyleSheet("background-color: rgb(203, 203, 203);")
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_13.addWidget(self.widget_6, 1, 0, 1, 4)

        spacerItem31 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_13.addItem(spacerItem31, 2, 2, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem32, 3, 0, 1, 1)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_42 = QtWidgets.QLabel(self.groupBox_4)
        self.label_42.setObjectName("label_42")
        self.gridLayout_14.addWidget(self.label_42, 1, 5, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.groupBox_4)
        self.label_44.setObjectName("label_44")
        self.gridLayout_14.addWidget(self.label_44, 1, 7, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.groupBox_4)
        self.label_41.setObjectName("label_41")
        self.gridLayout_14.addWidget(self.label_41, 1, 1, 1, 1)

        # Slider h for accel for theta=0
        self.horizontalSlider_4 = QtWidgets.QSlider(self.groupBox_4)
        self.horizontalSlider_4.setMinimum(2)
        self.horizontalSlider_4.setMaximum(8)
        self.horizontalSlider_4.setSingleStep(1)
        self.horizontalSlider_4.setPageStep(1)
        self.horizontalSlider_4.setProperty("value", 2)
        self.horizontalSlider_4.setSliderPosition(2)
        self.horizontalSlider_4.setTracking(False)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setInvertedAppearance(False)
        self.horizontalSlider_4.setInvertedControls(False)
        self.horizontalSlider_4.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider_4.setTickInterval(1)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        # Calls update_g_onPlane_vis() function when slider for h when theta=0 in this tab is moved
        self.horizontalSlider_4.valueChanged.connect(self.update_g_onPlane_vis) # or sliderReleased insted of valueChanged
        self.gridLayout_14.addWidget(self.horizontalSlider_4, 0, 1, 1, 7)

        self.label_43 = QtWidgets.QLabel(self.groupBox_4)
        self.label_43.setObjectName("label_43")
        self.gridLayout_14.addWidget(self.label_43, 1, 4, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.groupBox_4)
        self.label_47.setObjectName("label_47")
        self.gridLayout_14.addWidget(self.label_47, 1, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.groupBox_4)
        self.label_45.setObjectName("label_45")
        self.gridLayout_14.addWidget(self.label_45, 1, 2, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.groupBox_4)
        self.label_46.setObjectName("label_46")
        self.gridLayout_14.addWidget(self.label_46, 1, 8, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.groupBox_4)
        self.label_39.setObjectName("label_39")
        self.gridLayout_14.addWidget(self.label_39, 1, 6, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.groupBox_4)
        self.label_40.setObjectName("label_40")
        self.gridLayout_14.addWidget(self.label_40, 1, 3, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_14, 3, 1, 1, 2)
        spacerItem33 = QtWidgets.QSpacerItem(20, 35, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_13.addItem(spacerItem33, 4, 2, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_4, 0, 1, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_10, 1, 0, 1, 3)
        self.tabWidget.addTab(self.tab_3, "")

        self.update_g_onSphere_vis()
        self.update_g_onPlane_vis()

        # Tab Calc Pot & Accel
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")

        # Button Calculate
        self.pushButton = QtWidgets.QPushButton(self.groupBox_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        # Calls Calculate_pot_g() function when calculated button is pressed
        self.pushButton.clicked.connect(self.Calculate_pot_g)
        self.gridLayout_16.addWidget(self.pushButton, 1, 4, 1, 1)

        spacerItem34 = QtWidgets.QSpacerItem(180, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem34, 0, 4, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_50.sizePolicy().hasHeightForWidth())
        self.label_50.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.gridLayout_16.addWidget(self.label_50, 1, 0, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.groupBox_7)
        self.label_54.setObjectName("label_54")
        self.gridLayout_16.addWidget(self.label_54, 2, 2, 1, 1)

        # LineEdit Polar angle - Theta
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setText("45")
        self.gridLayout_16.addWidget(self.lineEdit_2, 1, 1, 1, 1)

        self.label_51 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_51.sizePolicy().hasHeightForWidth())
        self.label_51.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.gridLayout_16.addWidget(self.label_51, 2, 0, 1, 1)

        # LineEdit Azimuth angle - Phi
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_3.setText("60")
        self.gridLayout_16.addWidget(self.lineEdit_3, 2, 1, 1, 1)

        self.label_58 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)

        # Label Pot Calculate
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.gridLayout_16.addWidget(self.label_58, 0, 7, 1, 1)

        self.label_53 = QtWidgets.QLabel(self.groupBox_7)
        self.label_53.setObjectName("label_53")
        self.gridLayout_16.addWidget(self.label_53, 1, 2, 1, 1)

        # Label Accel Calculate
        self.label_59 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont() 
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.gridLayout_16.addWidget(self.label_59, 2, 7, 1, 1)

        self.label_57 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.gridLayout_16.addWidget(self.label_57, 2, 6, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_49.sizePolicy().hasHeightForWidth())
        self.label_49.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.gridLayout_16.addWidget(self.label_49, 0, 0, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_55.sizePolicy().hasHeightForWidth())
        self.label_55.setSizePolicy(sizePolicy)
        self.label_55.setObjectName("label_55")
        self.gridLayout_16.addWidget(self.label_55, 0, 8, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.groupBox_7)
        self.label_52.setObjectName("label_52")
        self.gridLayout_16.addWidget(self.label_52, 0, 2, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.gridLayout_16.addWidget(self.label_56, 0, 6, 1, 1)

        # LineEdit Heigth - h
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setText("100")
        self.gridLayout_16.addWidget(self.lineEdit, 0, 1, 1, 1)

        self.label_60 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_60.sizePolicy().hasHeightForWidth())
        self.label_60.setSizePolicy(sizePolicy)
        self.label_60.setObjectName("label_60")
        self.gridLayout_16.addWidget(self.label_60, 2, 8, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem35, 0, 3, 1, 1)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem36, 0, 5, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_16, 0, 1, 1, 1)
        spacerItem37 = QtWidgets.QSpacerItem(420, 10, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem37, 0, 2, 1, 1)
        self.gridLayout_20.addWidget(self.groupBox_7, 2, 1, 1, 4)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_19.setObjectName("gridLayout_19")

        # Widget calculate accel
        self.widget_8 = MplCanvas(self)
        self.widget_8.setStyleSheet("background-color: rgb(203, 203, 203);")
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_19.addWidget(self.widget_8, 0, 0, 1, 1)

        self.gridLayout_20.addWidget(self.groupBox_6, 1, 3, 1, 2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_18.setObjectName("gridLayout_18")

        # Widget calculate pot
        self.widget_7 = MplCanvas(self)
        self.widget_7.setStyleSheet("background-color: rgb(203, 203, 203);")
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_18.addWidget(self.widget_7, 0, 0, 1, 1)

        self.gridLayout_20.addWidget(self.groupBox_5, 1, 1, 1, 2)
        self.label_61 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.gridLayout_20.addWidget(self.label_61, 0, 2, 1, 2)
        spacerItem38 = QtWidgets.QSpacerItem(332, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem38, 0, 1, 1, 1)
        spacerItem39 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_20.addItem(spacerItem39, 0, 4, 1, 1)
        spacerItem40 = QtWidgets.QSpacerItem(0, 141, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_20.addItem(spacerItem40, 2, 0, 1, 1)
        spacerItem41 = QtWidgets.QSpacerItem(0, 551, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_20.addItem(spacerItem41, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)

        self.Calculate_pot_g()

        self.retranslateUi()
        layout = QHBoxLayout()
        layout.addWidget(self.centralwidget)
        self.setLayout(layout)
        self.tabWidget.setCurrentIndex(0)

        # Auxiliar Variables
        self.open = False
        self.exit = False

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "GeoPotential"))
        self.label.setText(_translate("MainWindow", "GEOID"))
        self.label_3.setText(_translate("MainWindow", "Geoid (Not On Real Scale)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Geoid"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Gravitational Potential in a Sphere of Radius 6378 km"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Replace J2 Coefficient by:"))
        self.label_80.setText(_translate("MainWindow", "        C43"))
        self.label_77.setText(_translate("MainWindow", "       C32"))
        self.label_79.setText(_translate("MainWindow", "       C41"))
        self.label_81.setText(_translate("MainWindow", "        C50"))
        self.label_78.setText(_translate("MainWindow", "       C40"))
        self.label_82.setText(_translate("MainWindow", "        C52"))
        self.label_83.setText(_translate("MainWindow", "        C54"))
        self.label_76.setText(_translate("MainWindow", "      C30"))
        self.label_74.setText(_translate("MainWindow", "C20"))
        self.label_75.setText(_translate("MainWindow", "     C21"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Gravitational Acceleration in a Sphere of Radius 6378 km"))
        self.label_62.setText(_translate("MainWindow", "Coefficients Visualization"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Coefficients Visualization"))
        self.label_2.setText(_translate("MainWindow", "Potential Visualization"))
        self.groupBox.setTitle(_translate("MainWindow", "Potential on a Sphere of Heigth h"))
        self.label_11.setText(_translate("MainWindow", "227"))
        self.label_13.setText(_translate("MainWindow", "229"))
        self.label_9.setText(_translate("MainWindow", "225"))
        self.label_4.setText(_translate("MainWindow", "220"))
        self.label_14.setText(_translate("MainWindow", "230"))
        self.label_7.setText(_translate("MainWindow", "223"))
        self.label_12.setText(_translate("MainWindow", "228"))
        self.label_10.setText(_translate("MainWindow", "226"))
        self.label_6.setText(_translate("MainWindow", "222"))
        self.label_5.setText(_translate("MainWindow", "221"))
        self.label_8.setText(_translate("MainWindow", "224"))
        self.label_15.setText(_translate("MainWindow", "km"))
        self.label_16.setText(_translate("MainWindow", "   h"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Potential on a Plane with Polar Angle = 0º, from Earth Radius to Heigth h"))
        self.label_22.setText(_translate("MainWindow", "    7000"))
        self.label_19.setText(_translate("MainWindow", "4000"))
        self.label_17.setText(_translate("MainWindow", "2000"))
        self.label_21.setText(_translate("MainWindow", "   6000"))
        self.label_20.setText(_translate("MainWindow", "  5000"))
        self.label_23.setText(_translate("MainWindow", "   8000"))
        self.label_18.setText(_translate("MainWindow", "3000"))
        self.label_24.setText(_translate("MainWindow", "km"))
        self.label_25.setText(_translate("MainWindow", "        h"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Potential Visualization"))
        self.label_48.setText(_translate("MainWindow", "Acceleration Visualization"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Potential on a Sphere of Heigth h"))
        self.label_26.setText(_translate("MainWindow", "227"))
        self.label_27.setText(_translate("MainWindow", "229"))
        self.label_28.setText(_translate("MainWindow", "225"))
        self.label_29.setText(_translate("MainWindow", "220"))
        self.label_30.setText(_translate("MainWindow", "230"))
        self.label_31.setText(_translate("MainWindow", "223"))
        self.label_32.setText(_translate("MainWindow", "228"))
        self.label_33.setText(_translate("MainWindow", "226"))
        self.label_34.setText(_translate("MainWindow", "222"))
        self.label_35.setText(_translate("MainWindow", "221"))
        self.label_36.setText(_translate("MainWindow", "224"))
        self.label_37.setText(_translate("MainWindow", "km"))
        self.label_38.setText(_translate("MainWindow", "   h"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Potential on a Plane with Polar Angle = 0.057º (due to singularity for 0º), from Earth Radius to Heigth h"))
        self.label_42.setText(_translate("MainWindow", "   6000"))
        self.label_44.setText(_translate("MainWindow", "   8000"))
        self.label_41.setText(_translate("MainWindow", "2000"))
        self.label_43.setText(_translate("MainWindow", "  5000"))
        self.label_47.setText(_translate("MainWindow", "        h"))
        self.label_45.setText(_translate("MainWindow", "3000"))
        self.label_46.setText(_translate("MainWindow", "km"))
        self.label_39.setText(_translate("MainWindow", "    7000"))
        self.label_40.setText(_translate("MainWindow", "4000"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Acceleration Visualization"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Parameters"))
        self.pushButton.setText(_translate("MainWindow", "Calculate"))
        self.label_50.setText(_translate("MainWindow", "Polar Angle"))
        self.label_54.setText(_translate("MainWindow", "degrees, from -180º to 180º"))
        self.label_51.setText(_translate("MainWindow", "Azimuth Angle  "))
        self.label_53.setText(_translate("MainWindow", "degrees, from -90º to 90º"))
        self.label_57.setText(_translate("MainWindow", "Acceleration  ="))
        self.label_49.setText(_translate("MainWindow", "Heigth"))
        self.label_55.setText(_translate("MainWindow", "  Nm/kg"))
        self.label_52.setText(_translate("MainWindow", "km, h>0"))
        self.label_56.setText(_translate("MainWindow", "Potential        ="))
        self.label_60.setText(_translate("MainWindow", "  m/s^2"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Gravitational Acceleration"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Gravitational Potential"))
        self.label_61.setText(_translate("MainWindow", "Calculate Gravitational Potential & Acceleration"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Calculate Gravitational Potential & Acceleration"))
    
    # Calls function load_txt() [from GeoPotential_utils] for the corresponding data file and plot Undulation matplotlib plot and geoid mayavi mesh
    def set_Undulation(self):
        path = './data/GeoPotencial-data/'
        # sets angles PHI anf THETA for the class
        self.PHI = load_txt(path+'PHI.txt')
        self.THETA = load_txt(path+'THETA.txt')
        path = './data/GeoPotencial-data/Geoid&Undulation/'
        N = load_txt(path+'N.txt')
        map = Basemap(projection='cyl',llcrnrlat=-90,urcrnrlat=90,\
            llcrnrlon=-180,urcrnrlon=180,resolution='c',ax=self.widget.axes)
        map.drawcoastlines()
        clrbr = cm.ScalarMappable(cmap=cm.jet)
        clrbr.set_array([-100, 80])
        cbar = self.widget.fig.colorbar(clrbr, orientation='horizontal')
        cbar.set_label('Geoid height [m]')
        self.widget.axes.set_title(f'Undulation')
        self.widget.axes.pcolormesh(self.PHI*180/np.pi, self.THETA*180/np.pi, N, cmap=cm.jet)
    
    # calls function get_slider_coeff(), load_txt [from GeoPotential_utils]
    # Plots matpolotlib Gravitational Potential and Gravitational Acceleration depending on the coefficient
    def update_coeff_vis(self):
        coeff = get_slider_coeff(self.horizontalSlider_5.value())
        path = './data/GeoPotencial-data/Coeffs-Vis/'
        Pot = load_txt(f'{path}Potential/P-{coeff}.txt')
        g = load_txt(f'{path}Acceleration/A-{coeff}.txt')

        self.widget_11.fig.clf()
        self.widget_11.axes = self.widget_11.fig.add_subplot(111)
        map_p = Basemap(projection='cyl',llcrnrlat=-90,urcrnrlat=90,\
            llcrnrlon=-180,urcrnrlon=180,resolution='c',ax=self.widget_11.axes)
        map_p.drawcoastlines()
        clrbr = cm.ScalarMappable(cmap=cm.RdBu)
        clrbr.set_array(Pot)
        cbar = self.widget_11.fig.colorbar(clrbr, orientation='horizontal')
        cbar.set_label('Gravitational Potential [Nm/kg]')
        self.widget_11.axes.pcolormesh(self.PHI*180/np.pi, self.THETA*180/np.pi, Pot, cmap=cm.RdBu)
        self.widget_11.draw()

        self.widget_12.fig.clf()
        self.widget_12.axes = self.widget_12.fig.add_subplot(111)
        map_g = Basemap(projection='cyl',llcrnrlat=-90,urcrnrlat=90,\
            llcrnrlon=-180,urcrnrlon=180,resolution='c',ax=self.widget_12.axes)
        map_g.drawcoastlines()
        clrbr = cm.ScalarMappable(cmap=cm.jet)
        clrbr.set_array(g)
        cbar = self.widget_12.fig.colorbar(clrbr, orientation='horizontal')
        cbar.set_label('Gravitational Acceleration [m/s^2]')
        self.widget_12.axes.pcolormesh(self.PHI*180/np.pi, self.THETA*180/np.pi, g, cmap=cm.jet)
        self.widget_12.draw()
    
    # Calls function load_txt() and depending on the slider value selected plots matplotlib Gravitational Potential plot
    def update_pot_onSphere_vis(self):
        h = self.horizontalSlider.value()
        path = './data/GeoPotencial-data/Pot-Vis/P-h/'
        Pot = load_txt(f'{path}P-h{h}.txt')
        vmax = -60258744.753098436
        vmin = -60442292.09159016

        self.widget_3.fig.clf()
        self.widget_3.axes = self.widget_3.fig.add_subplot(111, projection = 'mollweide')
        self.widget_3.axes.set_title(f'h = {h} Km')
        clrbr = cm.ScalarMappable(cmap=cm.RdBu)
        clrbr.set_array(np.linspace(vmin,vmax,100))
        cbar = self.widget_3.fig.colorbar(clrbr, orientation='horizontal')
        cbar.set_label('Gravitational Potential [Nm/kg]')
        self.widget_3.axes.pcolormesh(self.PHI, self.THETA, Pot, cmap=cm.RdBu, vmin=vmin, vmax=vmax)
        self.widget_3.axes.grid(color='k')
        self.widget_3.draw()
    
    # Calls function load_txt() and depending on the slider value selected plots matplotlib Gravitational Potential plot
    def update_pot_onPlane_vis(self):
        h = int(self.horizontalSlider_2.value())*1000
        path = f'./data/GeoPotencial-data/Pot-Vis/P-Theta=0/h-{h}/'
        Pot = load_txt(path+'P.txt')
        X = load_txt(path+'X.txt')
        Y = load_txt(path+'Y.txt')
        vmax = -27725589.761912752
        vmin = -62529420.408364825
        lim = R_T*1e-3 + 8000

        self.widget_4.fig.clf()
        self.widget_4.axes = self.widget_4.fig.add_subplot(111)
        self.widget_4.axes.set_title(f'Polar Angle = {0}')
        self.widget_4.axes.set_xlabel('X [Km]')
        self.widget_4.axes.set_ylabel('Y [Km]')
        self.widget_4.axes.set_xlim(xmin=-lim,xmax=lim)
        self.widget_4.axes.set_ylim(ymin=-lim,ymax=lim)
        clrbr = cm.ScalarMappable(cmap=cm.RdBu)
        clrbr.set_array(np.linspace(vmin,vmax,100))
        cbar = self.widget_4.fig.colorbar(clrbr, orientation='horizontal')
        cbar.set_label('Gravitational Potential [Nm/kg]')
        self.widget_4.axes.pcolormesh(X, Y, Pot, cmap=cm.RdBu, vmin=vmin, vmax=vmax)
        self.widget_4.axes.grid(color='k')
        self.widget_4.draw()
    
    # Calls function load_txt() and depending on the slider value selected plots matplotlib Gravitational Acceleration plot
    def update_g_onSphere_vis(self):
        h = self.horizontalSlider_3.value()
        path = './data/GeoPotencial-data/Acel-Vis/A-h/'
        g = load_txt(f'{path}A-h{h}.txt')
        vmax = 9.170099309219546
        vmin = 9.10043938979901

        self.widget_5.fig.clf()
        self.widget_5.axes = self.widget_5.fig.add_subplot(111, projection = 'mollweide')
        self.widget_5.axes.set_title(f'h = {h} Km')
        clrbr = cm.ScalarMappable(cmap=cm.jet)
        clrbr.set_array(np.linspace(vmin,vmax,100))
        cbar = self.widget_5.fig.colorbar(clrbr, orientation='horizontal')
        cbar.set_label('Gravitational Acceleration [m/s^2]')
        self.widget_5.axes.pcolormesh(self.PHI, self.THETA, g, cmap=cm.jet, vmin=vmin, vmax=vmax)
        self.widget_5.axes.grid(color='k')
        self.widget_5.draw()
    
    # Calls function load_txt() and depending on the slider value selected plots matplotlib Gravitational Acceleration plot
    def update_g_onPlane_vis(self):
        h = int(self.horizontalSlider_4.value())*1000
        path = f'./data/GeoPotencial-data/Acel-Vis/A-Theta=0/h-{h}/'
        g = load_txt(path+'A.txt')
        X = load_txt(path+'X.txt')
        Y = load_txt(path+'Y.txt')
        vmax = 9.820921038576518
        vmin = 1.9287201310684448
        lim = R_T*1e-3 + 8000

        self.widget_6.fig.clf()
        self.widget_6.axes = self.widget_6.fig.add_subplot(111)
        self.widget_6.axes.set_title(f'Polar Angle ≈ {0}')
        self.widget_6.axes.set_xlabel('X [Km]')
        self.widget_6.axes.set_ylabel('Y [Km]')
        self.widget_6.axes.set_xlim(xmin=-lim,xmax=lim)
        self.widget_6.axes.set_ylim(ymin=-lim,ymax=lim)
        clrbr = cm.ScalarMappable(cmap=cm.jet)
        clrbr.set_array(np.linspace(vmin,vmax,100))
        cbar = self.widget_6.fig.colorbar(clrbr, orientation='horizontal')
        cbar.set_label('Gravitational Acceleration [m/s^2]')
        self.widget_6.axes.pcolormesh(X, Y, g, cmap=cm.jet, vmin=vmin, vmax=vmax)
        self.widget_6.axes.grid(color='k')
        self.widget_6.draw()
    
    # Calls function read_egm96_file(), get_pot() and get_accel() [from GeoPotential_utils]
    # Depends on h, theta and phi written by user
    # sets labels with corresponding results of Gravitational Potential and Acceleration Potential
    # plots matplotlib plots of Gravitational Potential and Acceleration Potential in a sphere surface and plots a black dot
    # that corresponds to the position selected by the user in phi and theta
    def Calculate_pot_g(self):
        h = self.lineEdit.text()
        theta = self.lineEdit_2.text()
        phi =  self.lineEdit_3.text()
        try:
            h = float(h)
            phi = float(phi)
            theta = float(theta)
            if h >= 0 and  theta >= -90 and theta <= 90 and phi >= -180 and phi <= 180:
                h = h*1000
                phi = phi*np.pi/180
                # Singularity in g fot theta = 0, so put theta = 0.057º
                if theta < 0.057 and theta >= 0:
                    theta_corr = 0.057*np.pi/180
                elif theta > -0.057 and theta < 0:
                    theta_corr = -0.057*np.pi/180
                else: theta_corr = theta*np.pi/180
                theta = theta*np.pi/180
                l, m, C, S = read_egm96_file(egm96_file_path, lmax)
                r = R_T + h
                pos_Pot = get_pot(l, m, C, S, theta, phi, MU, R_T, r)
                pos_g = get_accel(l, m, C, S, theta_corr, phi, MU, R_T, r)
                Pot = get_pot(l, m, C, S, self.THETA, self.PHI, MU, R_T, r)
                g = get_accel(l, m, C, S, self.THETA, self.PHI, MU, R_T, r)
                
                if theta == np.pi/2 or theta == -np.pi/2:
                    pos_g = np.nanmin(g)
                self.label_58.setText(str(pos_Pot))
                self.label_59.setText(str(pos_g))

                self.widget_7.fig.clf()
                self.widget_7.axes = self.widget_7.fig.add_subplot(111, projection = 'mollweide')
                self.widget_7.axes.set_title(f'h = {h*1e-3} Km')
                clrbr = cm.ScalarMappable(cmap=cm.RdBu)
                clrbr.set_array(Pot)
                cbar = self.widget_7.fig.colorbar(clrbr, orientation='horizontal')
                cbar.set_label('Gravitational Potential [Nm/kg]')
                self.widget_7.axes.pcolormesh(self.PHI, self.THETA, Pot, cmap=cm.RdBu)
                self.widget_7.axes.scatter(phi, theta, color = 'black')
                self.widget_7.axes.grid(color='k')
                self.widget_7.draw()

                self.widget_8.fig.clf()
                self.widget_8.axes = self.widget_8.fig.add_subplot(111, projection = 'mollweide')
                self.widget_8.axes.set_title(f'h = {h*1e-3} Km')
                clrbr = cm.ScalarMappable(cmap=cm.jet)
                clrbr.set_array(g)
                cbar = self.widget_8.fig.colorbar(clrbr, orientation='horizontal')
                cbar.set_label('Gravitational Acceleration [m/s^2]')
                self.widget_8.axes.pcolormesh(self.PHI, self.THETA, g, cmap=cm.jet)
                self.widget_8.axes.scatter(phi, theta, color = 'black')
                self.widget_8.axes.grid(color='k')
                self.widget_8.draw()

                self.prev_h = self.lineEdit.text()
                self.prev_theta = self.lineEdit_2.text()
                self.prev_phi = self.lineEdit_3.text()
            else:
                self.lineEdit.setText(self.prev_h)
                self.lineEdit_2.setText(self.prev_theta)
                self.lineEdit_3.setText(self.prev_phi)
        except ValueError:
            self.lineEdit.setText(self.prev_h)
            self.lineEdit_2.setText(self.prev_theta)
            self.lineEdit_3.setText(self.prev_phi)
    
    def closeEvent(self, event):
        if not self.exit:
            event.ignore()
            self.hide()
            self.open = False
        else:
            event.accept()

if __name__ == "__main__":
    app = QApplication([])
    main_w = GeoPotential_MainWindow()
    main_w.show()
    sys.exit(app.exec_())
